### ISSUE TITLE
Version 0.9.8: CHECKLIST

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#188]
Major items expected in the release:

- [ ] Ability to define a JSON-RPC server for network switching for eth protocol, with a default that uses Infura
- [ ] Switch to Go-ethereum HD Wallets
- [ ] Think about how to integrate our double-ratchet implementation into Whisper
