### ISSUE TITLE
Stale or published elsewhere `ApplicationMetadataMessage_COMMUNITY_DESCRIPTION` public messages

### ISSUE THREAD

**Issue by felicio** [status-im/status-go#4922]
# Problem

- In Store nodes, last `ApplicationMetadataMessage_COMMUNITY_DESCRIPTION` for `zQ3shZeEJqTC1xhGUjxuS4rtHSrhJ8vUYp64v6qWkLpvdy9L9` (Status CC Community) is from around `2024-02-28T14:57:13.580Z`
- Another Community (`zQ3shgz9XWZerfqsSpR2XKjfyiwtyiRNV6whj6BXREwnuLo5P`) gets recent updates

## Summary from comments below

- [x] don't have `ProtocolMessage#public_message` set
- [x] have `ProtocolMessage#encrypted_message['none'].payload` set but without any private material needed to decode it
- [x] aren't signed by the community's private key so cannot be verified https://github.com/status-im/status-web/pull/541
- [x] while `CommunityDescription#chats` are empty the `CommunityDescription#categories` are set https://github.com/status-im/status-go/issues/4943
- [x] while `CommunityDescription#members` are empty the `CommunityDescription#active_members_count` isn't https://github.com/status-im/status-go/issues/4944
- [x] possible `COMMUNITY_DESCRIPTION` messages larger than 7MB https://github.com/status-im/status-go/issues/4955

# Implementation

Known steps towards feature implementation.
What needs further specifying and investigating.

# Acceptance Criteria

Rules for the future PR to be accepted.

# Notes

- pubsub topic: `/waku/2/rs/16/32`
- content topic: `/waku/1/0x13267e91/rfc26`
- fleet: `shards.test`

# Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by felicio** [comment]
Cc @osmaczko

**Comment by felicio** [comment]
Is it possible that a content topic format would change for certain Communities?

**Comment by jrainville** [comment]
We changed fleet to use the new one called `shards-test`, so that might be it.

Also, that community is not really used anymore, so it's possible that Iuri shut down the control node for it cc @iurimatias

**Comment by felicio** [comment]
@jrainville the description mentions `shards.test`. 

Which community is used then, please?

**Comment by jrainville** [comment]
> Which community is used then, please?

@felicio this is the new community https://status.app/c/G4IAAMSIuW0ORJLY43bdG0nzRKzhlAOHMJAkwRaAHZJ7yqYUxajs35U_WeFesRAnUVV96woIFyIvCSUFsiKN4L-2ESkypLDwYw-S5xztCs8IqQXB99foPIShRGs8H6mTpoTgr1fieI3s7HWt0-cH-_Px_DjNaXrUAA==#zQ3shZeEJqTC1xhGUjxuS4rtHSrhJ8vUYp64v6qWkLpvdy9L9

**Comment by felicio** [comment]
@jrainville again, that's what the description references.

Could you please have a closer look at the issue?

**Comment by jrainville** [comment]
> @jrainville again, that's what the description references.
> 
> Could you please have a closer look at the issue?

Sorry for the confusion, you named the community `Status CC Community`, which is the name of the old community, so I thought you were talking about that one.

I'm not sure what's going on here then. We clearly receive the latest updates in peer to peer, since I can see all the new channels.

> Is it possible that a content topic format would change for certain Communities?

If we shard the community, yes that would be the case. I don't recall that we sharded this one however.

@iurimatias can you check the shard popup which topic it is using?

**Comment by felicio** [comment]
@jrainville thank you. One more thing to reiterate, however, this issue focuses primarily on Store nodes.

**Comment by osmaczko** [comment]
The shard is not set, the `pubSubTopic` we fetch community info from is `/waku/2/rs/16/64`
https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/protocol/common/shard/shard.go#L58-L63

https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/protocol/common/shard/shard.go#L51

**Comment by jrainville** [comment]
> pubsub topic: "/waku/2/rs/16/32"
> we fetch community info from is /waku/2/rs/16/64

@felicio can you check if you update the topic if it works?

**Comment by osmaczko** [comment]
Sorry, I might have misinterpreted the code ([the code](https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/protocol/common/shard/shard.go#L54-L63) is misleading tbh - which one is the default? :dizzy_face: ). I just double-checked, and we publish `CommunityDescription` on `/waku/2/rs/16/32`. I got it mixed up with where we share `ApplicationMetadataMessage_COMMUNITY_PUBLIC_SHARD_INFO`.

**Comment by osmaczko** [comment]
@felicio I am able to fetch `CommunityDescription` from today:

```
store node: store-01.do-ams3.shards.test
description envelope: 0xc06f05cb5f15eab1424c57acb8f05bb11484786cffdba97a4c79d73565a1e4cf
timestamp: 1710508493775973252 (2024-03-15 13:14:53.775973252 +0000 UTC)
size: 530204 bytes
contentTopic: /waku/1/0x13267e91/rfc26
pubsubTopic: /waku/2/rs/16/32
```

**Comment by felicio** [comment]
@osmaczko I saw some recent messages of similar sizes for that community, but again since around `2024-02-28T14:57:13.580Z` they

- don't have `ProtocolMessage#public_message` set
- have `ProtocolMessage#encrypted_message['none'].payload` set but without any private material needed to decode it
- aren't signed by the community's private key so cannot be verified

And as a side note

- while `CommunityDescription#chats` are empty the `CommunityDescription#categories` are set
- while `CommunityDescription#members` are empty the `CommunityDescription#active_members_count` isn't

**Comment by osmaczko** [comment]
> * don't have `ProtocolMessage#public_message` set
> * have `ProtocolMessage#encrypted_message['none'].payload` set but without any private material needed to decode it

We [don't wrap](https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/protocol/messenger_communities.go#L119) `CommunityDescription` into `ProtocolMessage` when we publish the org :thinking: Not sure what is the logic in status-web, but I would expect `ProtocolMessage` [to be skipped](https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/protocol/v1/status_message.go#L123-L127) altogether due to protobuf unmarshaling fail.

However, if it used to work, I am pretty sure, it is not working now because of [messages segmentation](https://github.com/status-im/status-go/pull/4285).

> * aren't signed by the community's private key so cannot be verified

Oh, I see. The behavior changed a few months ago. Once the owner-token is minted, the signer of the community is no longer the community's private key. The signer becomes the owner of the token. I'll send you a link to the presentation about that offline.

> * while CommunityDescription#chats are empty the CommunityDescription#categories are set
> * while CommunityDescription#members are empty the CommunityDescription#active_members_count isn't

Could you share the `CommunityDescription` protobuf you are referring to, please?

**Comment by felicio** [comment]
@osmaczko 

> We [don't wrap](https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/protocol/messenger_communities.go#L119) CommunityDescription into ProtocolMessage

Step into https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/protocol/messenger_communities.go#L134 if you can see the wrapping there.

> However, if it used to work,

It still works the same for `zQ3shgz9XWZerfqsSpR2XKjfyiwtyiRNV6whj6BXREwnuLo5P`, but works unexpectedly, as listed above, for `zQ3shZeEJqTC1xhGUjxuS4rtHSrhJ8vUYp64v6qWkLpvdy9L9`.

> The behavior changed a few months ago.

How do you validate the message then?

> Could you share the CommunityDescription protobuf you are referring to, please?

Attaching the top-most waku (e.g. "`ProtocolMessage` > `ApplicationMetadataMessage` > `CommunityDescription`" message [payload.txt](https://github.com/status-im/status-go/files/14627896/payload.txt) – there's nothing specific about "status-web".

**Comment by osmaczko** [comment]
> Step into ... if you can see the wrapping there.

Message is wrapped only into `ApplicationMetadataMessage`. `ProtocolMessage` layer [is skipped](https://github.com/status-im/status-go/blob/9a133d519151840dc968dd8f5dd236eb4089a925/protocol/common/message_sender.go#L693-L705).

> It still works the same for `zQ3shgz9XWZerfqsSpR2XKjfyiwtyiRNV6whj6BXREwnuLo5P`, but works unexpectedly, as listed above, for `zQ3shZeEJqTC1xhGUjxuS4rtHSrhJ8vUYp64v6qWkLpvdy9L9`.

That's most likely because `zQ3shgz9XWZerfqsSpR2XKjfyiwtyiRNV6whj6BXREwnuLo5P` is still small enough to stay unsegmented.

> How do you validate the message then?

I sent you the link to the video with detailed explanations. Long story short, we queue `CommunityDescription` messages until we know the owner, then we validate the message against that known owner. Code paths:
- queue: https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/protocol/communities/manager.go#L1774
https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/protocol/communities/manager.go#L1782
- owner verification loop: https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/protocol/communities/manager.go#L475
- community validation against current owner: https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/protocol/communities/manager.go#L515

**Comment by felicio** [comment]
@osmaczko 

> Message is wrapped only into `ApplicationMetadataMessage`. 

So this https://github.com/status-im/status-go/blob/9a133d519151840dc968dd8f5dd236eb4089a925/protocol/common/message_sender.go#L662 is not run?

> `ProtocolMessage` layer [is skipped](https://github.com/status-im/status-go/blob/9a133d519151840dc968dd8f5dd236eb4089a925/protocol/common/message_sender.go#L693-L705).

So it would not fall into https://github.com/status-im/status-go/blob/9a133d519151840dc968dd8f5dd236eb4089a925/protocol/common/message_sender.go#L668 because of https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/protocol/messenger_communities.go#L131 ?

> is still small enough to stay unsegmented.

- Isn't the limit for segmentation like 7 MB?
- Wasn't the message you talked about like 500 KB?
- Why would those messages be split?

> That's most likely because

Let me point out again, even those types of messages for `zQ3shZeEJqTC1xhGUjxuS4rtHSrhJ8vUYp64v6qWkLpvdy9L9` aren't split.

Also, based on what you've shared so far, I believe you might have got the description from `COMMUNITY_EVENTS_MESSAGE_REJECTED` instead of `COMMUNITY_DESCRIPTION`.

---

Let me know if you'd prefer a short meeting.

**Comment by osmaczko** [comment]
I double checked and indeed we wrap the Description into `ProtocolMessage` :sweat:  It [has changed recently](https://github.com/status-im/status-go/commit/605fe40e3222fef387db696fce7ba74e72a50f95#diff-e8ae84ba629f58c08abd2b2b3864896c92dd9b3898cf7b450d378f76004bf312) for encrypted communities, we didn't do that before (public communities are not wrapped into `ProtocolMessage` I believe). The wrapping of `ApplicationMetadataMessage` happens here:
https://github.com/status-im/status-go/blob/224103d03622ccd6f5f297c65074700216245464/protocol/common/message_sender.go#L684
and that's how it is constructed exactly:
https://github.com/status-im/status-go/blob/224103d03622ccd6f5f297c65074700216245464/protocol/encryption/protocol.go#L322-L333

I also checked how we exactly process the message and indeed it is not segmented.
Handling of `description envelope   1: 0xf8e170716e3caa9d49e12b5ec1aa1ae680933dc5c973d6f23faa97c315c4cb12, timestamp: 1710530403844026612 (2024-03-15 19:20:03.844026612 +0000 UTC), size: 532508 bytes, contentTopic: /waku/1/0x13267e91/rfc26, pubsubTopic: /waku/2/rs/16/32`:
```
2024-03-18T10:13:24.530+0100	INFO	user-waku-0	wakuv2/waku.go:1103	received waku2 store message	{"envelopeHash": "0xf8e170716e3caa9d49e12b5ec1aa1ae680933dc5c973d6f23faa97c315c4cb12", "pubsubTopic": "/waku/2/rs/16/32", "timestamp": 1710530403844026612}
2024-03-18T10:13:24.530+0100	DEBUG	user-waku-0	wakuv2/waku.go:1327	received new envelope	{"messageType": 1, "envelopeHash": "0xf8e170716e3caa9d49e12b5ec1aa1ae680933dc5c973d6f23faa97c315c4cb12", "contentTopic": "/waku/1/0x13267e91/rfc26", "timestamp": 1710530403844026612}

2024-03-18T10:13:24.568+0100	DEBUG	user-messenger-0	transport/transport.go:262	message not cached	{"Transport": {"site": "retrieveRawAll", "hash": "0xf8e170716e3caa9d49e12b5ec1aa1ae680933dc5c973d6f23faa97c315c4cb12"}}
2024-03-18T10:13:24.568+0100	DEBUG	user-messenger-0	common/message_sender.go:1362	handling message segment	{"site": "handleSegmentationLayer", "hash": "0xf8e170716e3caa9d49e12b5ec1aa1ae680933dc5c973d6f23faa97c315c4cb12", "EntireMessageHash": "0x", "Index": 0, "SegmentsCount": 0}
2024-03-18T10:13:24.568+0100	DEBUG	user-messenger-0	common/message_sender.go:902	failed to handle segmentation layer message	{"site": "handleMessage", "hash": "0xf8e170716e3caa9d49e12b5ec1aa1ae680933dc5c973d6f23faa97c315c4cb12", "error": "invalid segments count", "errorVerbose": "invalid segments count"}
2024-03-18T10:13:24.569+0100	DEBUG	user-messenger-0	encryption/protocol.go:714	received a protocol message	{"Protocol": {"site": "HandleMessage", "sender-public-key": "0x04953f5f0d355b37c39d1d6460a31ed1114455f8263b3fd1b84406c5f12c9eb7dfb76ba7513b92186010928254984fe98aee069b4c7e20f9ea3da497c3ae769477", "my-installation-id": "844ba546-7516-4c2e-b067-5d24f7a162df", "messageID": "0xf8e170716e3caa9d49e12b5ec1aa1ae680933dc5c973d6f23faa97c315c4cb12"}}
2024-03-18T10:13:24.569+0100	DEBUG	user-messenger-0	common/message_sender.go:927	failed to handle datasync message	{"site": "handleMessage", "hash": "0xf8e170716e3caa9d49e12b5ec1aa1ae680933dc5c973d6f23faa97c315c4cb12", "error": "handling non-datasync message"}

2024-03-18T10:13:24.577+0100	DEBUG	user-messenger-0	protocol/messenger.go:3904	processing messages further	{"site": "RetrieveAll", "hash": "0xf8e170716e3caa9d49e12b5ec1aa1ae680933dc5c973d6f23faa97c315c4cb12", "count": 1}
2024-03-18T10:13:24.577+0100	INFO	user-messenger-0	protocol/messenger.go:3908	processing message	{"site": "RetrieveAll", "hash": "0xf8e170716e3caa9d49e12b5ec1aa1ae680933dc5c973d6f23faa97c315c4cb12", "message-id": "0xe242e775379544c62a196b1b315fe8a9926eeb34eaf7997bab514aea3a55d52d"}
2024-03-18T10:13:24.577+0100	INFO	user-messenger-0	protocol/messenger.go:3920	processing message	{"type": "COMMUNITY_DESCRIPTION", "senderID": "0x04953f5f0d355b37c39d1d6460a31ed1114455f8263b3fd1b84406c5f12c9eb7dfb76ba7513b92186010928254984fe98aee069b4c7e20f9ea3da497c3ae769477"}
2024-03-18T10:13:24.578+0100	INFO	user-messenger-0	protocol/messenger_handlers.go:668	handling CommunityDescription
2024-03-18T10:13:24.579+0100	DEBUG	user-messenger-0	communities/manager.go:1708	HandleCommunityDescriptionMessage	{"communityID": "0x02b5bdaf5a25fcfe2ee14c501fab1836b8de57f61621080c3d52073d16de0d98d6", "clock": 1710529833209}
2024-03-18T10:13:24.579+0100	DEBUG	user-messenger-0	communities/community_description_encryption.go:83	failed to decrypt community private data	{"keyIDSeqNo": "618891d4ace09777ffd614ad998e91d5c5b37123c2b7b61fe3886afd1d0bd1d1316", "error": "no ratchet key for given keyID", "errorVerbose": "no ratchet key for given keyID"}
2024-03-18T10:13:24.580+0100	DEBUG	user-messenger-0	communities/community_description_encryption.go:83	failed to decrypt community private data	{"keyIDSeqNo": "14cb119293e26251202d6036aebf6f870dfc92ff1e6d97adb40f751478be653e879", "error": "no ratchet key for given keyID", "errorVerbose": "no ratchet key for given keyID"}
2024-03-18T10:13:24.582+0100	INFO	user-messenger-0	communities/manager.go:1689	queuing community	{"id": "0x02b5bdaf5a25fcfe2ee14c501fab1836b8de57f61621080c3d52073d16de0d98d6", "name": "Status", "clock": 1710529833209, "signer": "0x04953f5f0d355b37c39d1d6460a31ed1114455f8263b3fd1b84406c5f12c9eb7dfb76ba7513b92186010928254984fe98aee069b4c7e20f9ea3da497c3ae769477"}
```

So going back to your points:
> - [ ] don't have ProtocolMessage#public_message set

Yes, that's the case. We don't set it.

> - [ ] have ProtocolMessage#encrypted_message['none'].payload set but without any private material needed to decode it

Paylod is unencrypted `ApplicationMetadataMessage` in that case. Since, we have `HRHeader` with `seqNo==0` we return payload as is when decrypting:
https://github.com/status-im/status-go/blob/224103d03622ccd6f5f297c65074700216245464/protocol/encryption/encryptor.go#L715-L718

Hope this explains the missing bits, if not, please let me know, we'll do a short meeting.

**Comment by jrainville** [comment]
Closing as the issue is on the Web side

**Comment by felicio** [comment]
@jrainville

> - [ ] don't have ProtocolMessage#public_message set
> - [ ] have ProtocolMessage#encrypted_message['none'].payload set but without any private material needed to decode it

@osmaczko confirmed that's the behavior now, but don't you guys think these public messages that don't carry any keys nor require any other private information to be decoded should have the same data structure as those for public communities?

> - [ ] while CommunityDescription#chats are empty the CommunityDescription#categories are set
> - [ ] while CommunityDescription#members are empty the CommunityDescription#active_members_count isn't

Did you also confirm these? And are you going to create follow-up issues?

> - [ ] possible COMMUNITY_DESCRIPTION messages larger than 7MB

Given fast lookups, why would a message with public community metadata ever be larger than 7MB? And if some of it is not public, shouldn't it be sent on another content topic?

**Comment by osmaczko** [comment]
> Given fast lookups, why would a message with public community metadata ever be larger than 7MB?

Waku message limit [defined in status-go is 1MiB](https://github.com/status-im/status-go/blob/f0d6a4f64f882fe249626a5fec8eaafba3f97824/wakuv2/common/const.go#L38). Message payload [is limited to 0.75MiB](https://github.com/status-im/status-go/blob/f0d6a4f64f882fe249626a5fec8eaafba3f97824/protocol/common/message_sender.go#L1342). We reached this limit in the past already: https://github.com/status-im/status-desktop/issues/12188. Also please note that in the future, the maximum size of a message might be reduced dramatically from 1MiB to 150KiB: https://github.com/status-im/status-desktop/issues/12188#issuecomment-1723418663. Currently, the size of Status' `CommunityDescription` is ~0.5MiB - we are close to the limit.

>  And if some of it is not public, shouldn't it be sent on another content topic?

We wanted to avoid the complexity of reconstructing the Community state from data being spread across multiple messages/topics. I suppose we could consider sending only the public data on another content topic if needed.

**Comment by osmaczko** [comment]
> Did you also confirm these? And are you going to create follow-up issues?

Indeed. Thanks for heads-up. Created issues: https://github.com/status-im/status-go/issues/4943, https://github.com/status-im/status-go/issues/4944

**Comment by felicio** [comment]
Thanks, clarified the data structure and if you decide not to create an issue for that too, I'll close this.

Also, this issue is not blocking.
