### ISSUE TITLE
Network overhead investigation

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-go#576]
# Problem

We have some network consumption measurement: https://github.com/status-im/status-react/issues/2931
Not it looks like we have significant network overhead. This should be tested: is this overhead caused by Status code or Ethereum code.
The issue is more about reliable testing for network consumption than monitoring.

# Implementation

We should test out network overhead brt Geth network consumption:
We already have https://github.com/JekaMas/ether_tester and should update it:

- [ ] Add support of test scenarios for Status containers https://github.com/status-im/status-go/issues/585
- [ ] Idle test scenarios for Geth and Status. With and without upstream. Geth with and without Whisper. https://github.com/status-im/status-go/issues/587
- [ ] Single 1-1 chat test scenarios for Geth and Status (60rpm per node). With and without upstream. https://github.com/status-im/status-go/issues/586
- [ ] 10 group chats(60 rpm per node) for Status with and without mail server. With and without upstream. https://github.com/status-im/status-go/issues/588
- [ ] Check if we can use some smaller number of peers to shrink network overhead https://github.com/status-im/status-go/issues/583

# Acceptance Criteria

Reliable network tests and answer how many peers do we need so that traffic is reasonable, but the connection is not affected.

# Notes
Part of https://github.com/status-im/ideas/issues/71

# Future Steps

Change peers list and create new network overhead issues if needed.

**Comment by oskarth** [comment]
^ @JekaMas @mandrigin what do you want to do with this issue?
