### ISSUE TITLE
Move from whisperV5 to whisperV6

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-go#634]
# Problem

Network overhead from whisper is significant. We tested whisperV6 and realized that it is suitable to reduce network overhead and perhaps CPU.

# Implementation

- [x] Move basic whisperV6 code into our repo https://github.com/status-im/status-go/issues/636
- [x] Apply notifications patch https://github.com/status-im/status-go/issues/637
- [x] Switch code to use whisperV6 https://github.com/status-im/status-go/issues/638
- [ ] Switch Status cluster and mail server node to WhisperV6 https://github.com/status-im/status-go/issues/640
- [x] Apply envelopes tracing patch https://github.com/status-im/status-go/issues/641
- [ ] Bottleneck in matching messages filters https://github.com/status-im/status-go/issues/642

# Acceptance Criteria

All tests are passed. Status application passed all tests and nothing is broken: chats, offline mailboxing, notifications.

Part of https://github.com/status-im/ideas/issues/71

**Comment by dshulyak** [comment]
It was implemented
