### ISSUE TITLE
EPIC: Implement Push Notification server infra and functionality

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go#846]
# Problem

Currently, Push Notifications are sent directly from the sender phone to FCM. This approach presents a few problems:
- the FCM server key lives on the Status executable (actually it is currently [in the source code](https://github.com/status-im/status-go/blob/develop/geth/api/backend.go#L26), exposing us to easy quota theft).
- the lack of an intermediary presents some limitations, such as making it much harder to correctly handle situations like a contact changing devices, public chats, or Push Notifications market.

This issue will close https://github.com/status-im/status-go/issues/343.

# Implementation

- [ ] (https://github.com/status-im/status-go/issues/847) Implement a Push Notification Server project (similar to mailserver) accepting a flag (`--pndispatcher <URL>`) which will take the endpoint of a configured [gorush](https://github.com/appleboy/gorush) instance.
- [ ] (https://github.com/status-im/status-go/issues/882) Implement E2E tests
- [x] Start broadcasting availability to serve as PN server
- [ ] Accept anonymous requests to register and maintain registration map (until a certain threshold to avoid malicious attacks).
- [ ] Accept and handle messages from registered devices to send notifications to a given device through the gorush endpoint.

# Acceptance Criteria

Server:
- broadcasts its availability until it reaches the maximum number of registered accounts;
- accepts and replies to registrations; and
- accepts and forwards notification requests to the configured gorush endpoint.

# Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

# Future Steps

Implement support in the status-react app to register with the PN server and send PN through it.

**Comment by dshulyak** [comment]
I commented on another issue initially. But please, implement this server as a standalone app, no need to embed it into statusd, imo it is already a problem that status-go is used both for mobile devices and our nodes, and we should aim to split it, not overload single repository with lots of unrelated things.

**Comment by pedropombeiro** [comment]
@dshulyak I agree, and don't worry, these issues are just placeholders for the upcoming work, the actual implementation details still need to be discussed.

**Comment by JekaMas** [comment]
Maybe it makes sence to implement notification server as Ethereum sub-service (like Whisper and Swarm) in separate repo. It can be more transparent for the community.
